name: ci

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  TZ: 'Asia/Tokyo'

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout 🛎
        uses: actions/checkout@master
        with:
          fetch-depth: 0

      - name: Setup node env 🏗
        id: setup_nodejs
        uses: actions/setup-node@v4
        with:
          node-version-file: '.tool-versions'

      - name: Cache node_modules 📦
        uses: actions/cache@v3
        id: npm-cache
        with:
          path: ~/.npm
          key: npm-${{ runner.os }}-node-${{ steps.setup_nodejs.outputs.node-version }}-${{ hashFiles('**/package-lock.json') }}

      - name: Install dependencies 👨🏻‍💻
        if: steps.npm-cache.outputs.cache-hit != 'true'
        run: npm ci

      - name: Run test 👀
        run: npm run test
