name: ci

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - name: Checkout 🛎
        uses: actions/checkout@master

      - name: Setup node env 🏗
        uses: actions/setup-node@v3.6.0
        with:
          node-version-file: '.nvmrc'

      - name: Cache node_modules 📦
        uses: actions/cache@v3
        id: npm-cache
        with:
          path: ~/.npm
          key: npm-${{ runner.os }}-node-${{ matrix.node-version }}-${{ hashFiles('**/package-lock.json') }}

      - name: Install npm 👨🏻‍💻
        run: npm i -g npm@latest

      - name: Install dependencies 👨🏻‍💻
        run: npm i

      - name: Run test 👀
        run: npm run test

        env:
          CI: true
